apiVersion: v1
kind: PersistentVolumeClaim # it is not an actula volumem, 
                            #it is just a clain that kubernetes tries to fullfill from the the host harddisk
metadata:
    name: database-persistent-volume-claim
spec:
    accessModes: # defines the access mode of nodes from persistent volume
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
